### PR TITLE
Add Live tag to events, add placeholder for empty event carousels

### LINKED ISSUE #181: carousel cards too big
Depending on the viewport width, some of the carousel cards might have a width too big so no other cards show. This makes it really difficult to understand the carousel is scrollable. There should be a max width of like 70vw or something on the cards so we guarantee at least two show up always

image

### PR DESCRIPTION
**Pull request by alexzhang1618**
## Changes
- Closes #181 
  - Added a max-width to event cards so they fit inside mobile screens and have space for the next card
  - Still trying to figure out how to make the bottom of the cards stretch out if other cards in the carousel have started wrapping
    - switching eventcard to flex didn't work, block has weird image alignment that I couldn't figure out
- Adding a placeholder for event carousels with no events
- Adding a Live tag for events that are happening right now

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have added new Cypress tests that are passing.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have documented any new functions in `/src/lib/*` and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

Screenshot 2024-03-27 at 9 12 24 PM
Screenshot 2024-03-27 at 9 22 41 PM
Screenshot 2024-03-27 at 10 16 24 PM

### CODE REVIEW

**Comment by SheepTester** [comment]
Since the badges can wrap now, can it get cut off on the pickup page

**Comment by alexzhang1618** [comment]
> Since the badges can wrap now, can it get cut off on the pickup page

No since the change is only for event cards inside the EventCarousel

**Review by SheepTester — APPROVED** [review]
lgtm

since you're letting badges wrap now, would it make sense to allow the event names/locations to wrap too?

image


> Still trying to figure out how to make the bottom of the cards stretch out if other cards in the carousel have started wrapping
> * switching eventcard to flex didn't work, block has weird image alignment that I couldn't figure out

1. `align-items: stretch` on `.slider`
2. remove `height: fit-content;` from `.container` for the event card to allow it to stretch
3. the image is aligned weirdly because `<button>` elements vertically center their content by default. you could do `display: flex; flex-direction: column;` on the event card, then add `width: 100%;` to `.info` so the text doesn't overflow

**Comment by alexzhang1618** [comment]
> since you're letting badges wrap now, would it make sense to allow the event names/locations to wrap too?

hmm maybe let's play around with this and figure out if we want it, for now I'll leave it out

**Pull request merged**
