### PR TITLE
Internal Server Error Page

### PR DESCRIPTION
**Pull request by farisashai**
custom 500 page makes it easier to recover to a stable client state by logging out (clearing all cookies)

can design something nicer later on

this page will be hit when serversideprops hits an exception such as 
- corrupted cookies
- existing but invalid auth token
- api goes down
- invalid api response

the first 2 cases are easily recoverable by logging out and the last 2 make the portal unusable anyways so they can't be solved by the user

# Type of Change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Logistics Change (A change to a README, description, or dev workflow setup like
      linting/formatting)
- [ ] Continuous Integration Change (Related to deployment steps or continuous integration
      workflows)
- [ ] Other: (Fill In) 

# Testing

I have tested that my changes fully resolve the linked issue ...

- [x] locally on Desktop.
- [ ] on the live deployment preview on Desktop.
- [ ] on the live deployment preview on Mobile.
- [ ] I have added new Cypress tests that are passing.

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have followed the style guidelines of this project.
- [x] I have documented any new functions in `/src/lib/*` and commented hard to understand areas
      anywhere else.
- [x] My changes produce no new warnings.

# Screenshots

### CODE REVIEW

**Review by alexzhang1618 — APPROVED** [review]
lgtm, is there a screenshot of the page?

**Comment by farisashai** [comment]
just go to /500

**Comment by alexzhang1618** [comment]
Screenshot 2024-01-20 at 8 37 47 AM

**Comment by alexzhang1618** [comment]
Can we make the link blue so it's clear that it's clickable?

**Pull request merged**
